{{- /*
NetworkPolicy for OnlyOffice Document Server
*/ -}}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "onlyoffice-documentserver.fullname" . }}
  labels:
    {{- include "onlyoffice-documentserver.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "onlyoffice-documentserver.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432  # PostgreSQL
        - protocol: TCP
          port: 5672  # RabbitMQ
        - protocol: TCP
          port: 443   # HTTPS
{{- end }}
