{{- /*
PersistentVolumeClaim for OnlyOffice Document Server data storage
*/ -}}
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "onlyoffice-documentserver.fullname" . }}-pvc
  labels:
    {{- include "onlyoffice-documentserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
